/**
 * Centralized calculator data structure
 * Makes it easy to add new calculators and organize by category
 */

export interface CalculatorInfo {
  name: string;
  description: string;
  href: string;
  category: string;
  subcategory?: string;
  isCore?: boolean;
  isDesignTool?: boolean;   // true = listed under Design Tools, excluded from Calculators index
  level?: "Fundamental" | "Applied" | "Specialized";
  tags?: string[];
}

export const calculatorCategories = [
  {
    id: "fluid-mechanics-i",
    name: "Fluid Properties & Statics",
    description: "Hydrostatics, buoyancy, pressure measurement, and surface effects",
    color: "blue",
  },
  {
    id: "fluid-mechanics-ii",
    name: "Flow Essentials",
    description: "Conservation laws, flow measurement, internal and external flow, and fluid forces",
    color: "green",
  },
  {
    id: "heat-mass-transfer",
    name: "Heat & Mass Transfer",
    description: "Convective heat and mass transfer, heat exchangers, and thermal analysis",
    color: "orange",
  },
  {
    id: "open-channel",
    name: "Open Channel Flow",
    description: "Free surface flows, channels, hydraulic structures, and coastal hydraulics",
    color: "teal",
  },
  {
    id: "compressible-flow",
    name: "Compressible Flow",
    description: "High-speed gas dynamics, shocks, isentropic relations, and nozzle flow",
    color: "red",
  },
  {
    id: "turbomachinery",
    name: "Turbomachinery",
    description: "Pumps, fans, turbines, and rotating machinery performance",
    color: "indigo",
  },
  {
    id: "pipe-networks",
    name: "Pipe & Duct Systems",
    description: "Pipe sizing, friction factors, series/parallel networks, and water hammer",
    color: "cyan",
  },
];

export const allCalculators: CalculatorInfo[] = [
  // Fluid Properties
  {
    name: "Fluid Properties at Temperature",
    description: "Density, dynamic/kinematic viscosity, thermal conductivity, specific heat, and Prandtl number for water, air, ethylene glycol 50%, engine oil, and seawater — interpolated from standard data tables.",
    href: "/calculators/fluid-properties",
    category: "fluid-mechanics-i",
    isCore: true,
    level: "Fundamental",
    tags: ["fluid properties", "density", "viscosity", "thermal conductivity", "Prandtl", "water", "air", "glycol", "temperature"],
  },

  {
    name: "Pipe Run Designer",
    description: "Chain pipe segments with fittings and elevation changes. Outputs velocity, Reynolds number, flow regime, friction factor, and cumulative pressure drop per segment.",
    href: "/calculators/pipe-run",
    category: "pipe-networks",
    isCore: true,
    level: "Applied",
    tags: ["pipe run", "pressure drop", "head loss", "fittings", "velocity", "Reynolds number", "pipe design", "pipe system"],
  },
  {
    name: "Fan & Blower System Curve",
    description: "Build an air duct system resistance curve, overlay a fan H-Q curve to find the operating point. Supports round and rectangular ducts, fittings, and altitude/temperature density correction.",
    href: "/calculators/fan-system-curve",
    category: "pipe-networks",
    isCore: true,
    level: "Applied",
    tags: ["fan curve", "system curve", "duct", "HVAC", "ventilation", "pressure drop", "duty point", "air density"],
  },
  {
    name: "Interactive Moody Chart",
    description: "Plot your operating point on the Moody diagram — enter Re and ε/D to read friction factor. Includes flow regime shading, roughness curves, and hover crosshair.",
    href: "/calculators/moody-chart",
    category: "pipe-networks",
    isCore: true,
    level: "Applied",
    tags: ["moody chart", "friction factor", "Colebrook-White", "Reynolds number", "relative roughness", "Darcy"],
  },
  {
    name: "Pressure Relief Valve Sizing",
    description: "API 520 Part I orifice area sizing for gas/vapour, steam, and liquid service. Selects the next standard API letter orifice designation.",
    href: "/calculators/pressure-relief-valve",
    category: "pipe-networks",
    level: "Specialized",
    tags: ["pressure relief valve", "PRV", "PSV", "API 520", "orifice", "safety valve", "relief load"],
  },

  // Fluid Mechanics I
  {
    name: "Reynolds Number — Internal (Pipe) Flow",
    description: "Calculate Reynolds number for internal pipe flow; classifies flow as laminar, transitional, or turbulent.",
    href: "/calculators/reynolds",
    category: "fluid-mechanics-i",
    isCore: true,
    level: "Fundamental",
    tags: ["dimensionless", "flow regime", "pipe flow"],
  },
  {
    name: "Reynolds Number — External Flow",
    description: "Calculate Reynolds number for external flow over flat plates, cylinders, and spheres; classifies boundary-layer regime and drag behaviour.",
    href: "/calculators/reynolds-external",
    category: "fluid-mechanics-i",
    level: "Fundamental",
    tags: ["dimensionless", "external flow", "boundary layer", "drag", "flat plate", "cylinder", "sphere"],
  },
  {
    name: "Continuity Equation",
    description: "Calculate flow rate, velocity, or area using the continuity equation for incompressible flow.",
    href: "/calculators/continuity",
    category: "fluid-mechanics-i",
    isCore: true,
    level: "Fundamental",
    tags: ["conservation", "mass flow"],
  },
  {
    name: "Bernoulli Equation",
    description: "Solve for pressure, velocity, or elevation using Bernoulli's equation along a streamline.",
    href: "/calculators/bernoulli",
    category: "fluid-mechanics-i",
    isCore: true,
    level: "Fundamental",
    tags: ["energy", "pressure", "streamline"],
  },
  {
    name: "Hydrostatic Pressure",
    description: "Calculate pressure at depth in a static fluid using hydrostatic pressure equation.",
    href: "/calculators/hydrostatic",
    category: "fluid-mechanics-i",
    level: "Fundamental",
    tags: ["statics", "pressure", "depth"],
  },
  {
    name: "Hydrostatic Force on Plane Surface",
    description: "Calculate the resultant force on a submerged plane surface and locate the center of pressure — for rectangular, circular, and triangular surfaces at any inclination.",
    href: "/calculators/hydrostatic-force",
    category: "fluid-mechanics-i",
    level: "Applied",
    tags: ["statics", "force", "center of pressure", "submerged surface", "inclined", "buoyancy"],
  },
  {
    name: "Viscosity Conversion",
    description: "Convert dynamic viscosity μ and kinematic viscosity ν across all common unit systems (Pa·s, cP, P, cSt, St, ft²/s …) and cross-convert between the two using fluid density.",
    href: "/calculators/viscosity-conversion",
    category: "fluid-mechanics-i",
    level: "Fundamental",
    tags: ["viscosity", "dynamic viscosity", "kinematic viscosity", "unit conversion", "cP", "cSt", "poise"],
  },
  {
    name: "Pipe Flow Rate",
    description: "Calculate volumetric flow rate in a pipe given velocity and cross-sectional area.",
    href: "/calculators/pipe-flow-rate",
    category: "fluid-mechanics-i",
    level: "Fundamental",
    tags: ["flow rate", "velocity", "area"],
  },
  {
    name: "Manometer",
    description: "Calculate pressure difference from manometer height difference and fluid density.",
    href: "/calculators/manometer",
    category: "fluid-mechanics-i",
    level: "Fundamental",
    tags: ["pressure", "measurement", "static"],
  },
  {
    name: "Buoyancy",
    description: "Calculate buoyant force on a submerged object using Archimedes' principle.",
    href: "/calculators/buoyancy",
    category: "fluid-mechanics-i",
    level: "Fundamental",
    tags: ["buoyancy", "force", "archimedes"],
  },
  {
    name: "Torricelli's Theorem",
    description: "Calculate exit velocity from a tank using Torricelli's theorem (ideal case).",
    href: "/calculators/torricelli",
    category: "fluid-mechanics-i",
    level: "Applied",
    tags: ["velocity", "tank", "orifice"],
  },
  {
    name: "Pitot Tube",
    description: "Calculate flow velocity from Pitot tube pressure difference measurement.",
    href: "/calculators/pitot-tube",
    category: "fluid-mechanics-i",
    level: "Applied",
    tags: ["velocity", "measurement", "pressure"],
  },
  {
    name: "Velocity Head",
    description: "Calculate velocity head from flow velocity using V²/(2g).",
    href: "/calculators/velocity-head",
    category: "fluid-mechanics-i",
    level: "Fundamental",
    tags: ["head", "velocity", "energy"],
  },
  {
    name: "Mass Flow Rate",
    description: "Calculate mass flow rate from density and volumetric flow rate.",
    href: "/calculators/mass-flow-rate",
    category: "fluid-mechanics-i",
    level: "Fundamental",
    tags: ["mass flow", "density", "flow rate"],
  },
  
  // Fluid Mechanics II
  {
    name: "Pipe Head Loss",
    description: "Calculate head loss in pipes using Darcy-Weisbach equation with friction factor.",
    href: "/calculators/pipe-head-loss",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["head loss", "friction", "darcy-weisbach"],
  },
  {
    name: "Friction Factor",
    description: "Calculate Darcy friction factor using Moody chart correlations (laminar or turbulent).",
    href: "/calculators/friction-factor",
    category: "pipe-networks",
    level: "Applied",
    tags: ["friction", "moody", "reynolds"],
  },
  {
    name: "Minor Losses",
    description: "Calculate minor head losses due to fittings, bends, and valves.",
    href: "/calculators/minor-losses",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["head loss", "fittings", "valves"],
  },
  {
    name: "Pump Power",
    description: "Calculate power required by a pump to deliver a specified flow rate and head.",
    href: "/calculators/pump-power",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["power", "pump", "energy"],
  },
  {
    name: "Poiseuille Flow",
    description: "Calculate laminar flow rate in a circular pipe using Hagen-Poiseuille equation.",
    href: "/calculators/poiseuille-flow",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["laminar", "pipe flow", "pressure drop"],
  },
  {
    name: "Orifice Flow",
    description: "Calculate flow rate through an orifice using pressure difference and discharge coefficient.",
    href: "/calculators/orifice-flow",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["orifice", "flow rate", "discharge"],
  },
  {
    name: "Venturi Flow",
    description: "Calculate flow rate through a venturi meter using pressure difference and geometry.",
    href: "/calculators/venturi-flow",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["venturi", "flow meter", "pressure"],
  },
  {
    name: "Drag on Sphere",
    description: "Calculate drag force on a sphere using drag coefficient and Reynolds number.",
    href: "/calculators/drag-sphere",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["drag", "external flow", "sphere"],
  },
  {
    name: "Stokes Law",
    description: "Calculate drag force on a sphere in creeping flow (Re < 1) using Stokes' law.",
    href: "/calculators/stokes-law",
    category: "fluid-mechanics-ii",
    level: "Specialized",
    tags: ["drag", "low re", "creeping flow"],
  },
  {
    name: "Mach Number",
    description: "Calculate Mach number for compressible flow; ratio of flow velocity to speed of sound.",
    href: "/calculators/mach-number",
    category: "compressible-flow",
    level: "Fundamental",
    tags: ["compressible", "mach", "speed of sound"],
  },
  
  // Froude belongs in Open Channel — it governs subcritical/supercritical classification
  {
    name: "Froude Number",
    description: "Calculate Froude number for open channel flow; ratio of inertial to gravitational forces.",
    href: "/calculators/froude-number",
    category: "open-channel",
    level: "Fundamental",
    tags: ["froude", "open channel", "dimensionless"],
  },
  // Weber belongs with flow essentials — surface/inertia ratio used across many domains
  {
    name: "Weber Number",
    description: "Calculate Weber number; ratio of inertial forces to surface tension forces.",
    href: "/calculators/weber-number",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["weber", "surface tension", "dimensionless"],
  },
  
  // Fluid Properties & Statics (surface effects belong here, not heat transfer)
  {
    name: "Surface Tension",
    description: "Calculate force due to surface tension along a contact line or perimeter.",
    href: "/calculators/surface-tension",
    category: "fluid-mechanics-i",
    level: "Applied",
    tags: ["surface tension", "force", "interface"],
  },
  {
    name: "Capillary Rise",
    description: "Calculate the height of liquid rise in a capillary tube due to surface tension.",
    href: "/calculators/capillary-rise",
    category: "fluid-mechanics-i",
    level: "Applied",
    tags: ["capillary", "surface tension", "rise"],
  },
  
  // Additional calculators to reach 50
  {
    name: "Flow Coefficient",
    description: "Calculate flow coefficient (Cv) for valves and flow control devices.",
    href: "/calculators/flow-coefficient",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["flow coefficient", "valves", "Cv"],
  },
  {
    name: "Discharge Coefficient",
    description: "Calculate discharge coefficient for flow through orifices and nozzles.",
    href: "/calculators/discharge-coefficient",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["discharge", "orifice", "nozzle"],
  },
  {
    name: "Pressure Recovery",
    description: "Calculate pressure recovery in diffusers and expanding sections.",
    href: "/calculators/pressure-recovery",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["pressure", "diffuser", "recovery"],
  },
  {
    name: "Ideal Gas Density",
    description: "Calculate gas density ρ = P/(RT) from absolute pressure and temperature. Includes presets for air, N₂, O₂, CO₂, H₂, He, CH₄, and steam.",
    href: "/calculators/ideal-gas-density",
    category: "fluid-mechanics-i",
    level: "Fundamental",
    tags: ["ideal gas", "density", "pressure", "temperature", "gas constant", "specific volume"],
  },
  {
    name: "Specific Gravity / Relative Density",
    description: "Calculate specific gravity SG = ρ/ρ_ref versus water or air; determine float/sink behaviour and API gravity for petroleum products.",
    href: "/calculators/specific-gravity",
    category: "fluid-mechanics-i",
    level: "Fundamental",
    tags: ["specific gravity", "relative density", "SG", "API gravity", "float", "sink"],
  },
  {
    name: "Metacentric Height",
    description: "Calculate GM = KB + BM − KG for rectangular and circular floating bodies to assess small-angle stability. Outputs KB, BM, KM, BG, displaced volume, and stability classification.",
    href: "/calculators/metacentric-height",
    category: "fluid-mechanics-i",
    level: "Applied",
    tags: ["metacentric height", "GM", "stability", "floating body", "buoyancy", "ship", "barge"],
  },
  {
    name: "Bulk Modulus & Compressibility",
    description: "Calculate bulk modulus K = ΔP/|ΔV/V₀|, compressibility β = 1/K, and speed of sound c = √(K/ρ) — from direct K input or from pressure and volume strain.",
    href: "/calculators/bulk-modulus",
    category: "fluid-mechanics-i",
    level: "Applied",
    tags: ["bulk modulus", "compressibility", "speed of sound", "fluid properties", "stiffness"],
  },
  {
    name: "Vapor Pressure & Cavitation Number",
    description: "Calculate cavitation number σ = (P − Pv) / (½ρV²) and NPSH to predict vapor bubble formation. Includes water vapor pressure table and device-specific risk thresholds.",
    href: "/calculators/cavitation-number",
    category: "fluid-mechanics-i",
    level: "Applied",
    tags: ["cavitation", "vapor pressure", "NPSH", "sigma", "bubbles", "pump"],
  },
  {
    name: "Euler Number",
    description: "Calculate Euler number; ratio of pressure to inertial forces.",
    href: "/calculators/euler-number",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["euler", "pressure", "dimensionless"],
  },
  {
    name: "Strouhal Number",
    description: "Calculate Strouhal number for unsteady flow and vortex shedding.",
    href: "/calculators/strouhal-number",
    category: "fluid-mechanics-ii",
    level: "Specialized",
    tags: ["strouhal", "unsteady", "vortex"],
  },
  {
    name: "Nusselt Number",
    description: "Calculate Nusselt number for convective heat transfer.",
    href: "/calculators/nusselt-number",
    category: "heat-mass-transfer",
    level: "Applied",
    tags: ["nusselt", "heat transfer", "convection"],
  },
  {
    name: "Prandtl Number",
    description: "Calculate Prandtl number; ratio of momentum to thermal diffusivity.",
    href: "/calculators/prandtl-number",
    category: "heat-mass-transfer",
    level: "Applied",
    tags: ["prandtl", "heat transfer", "dimensionless"],
  },
  {
    name: "Grashof Number",
    description: "Calculate Grashof number for natural convection flows.",
    href: "/calculators/grashof-number",
    category: "heat-mass-transfer",
    level: "Specialized",
    tags: ["grashof", "natural convection", "buoyancy"],
  },
  {
    name: "Rayleigh Number",
    description: "Calculate Rayleigh number; product of Grashof and Prandtl numbers.",
    href: "/calculators/rayleigh-number",
    category: "heat-mass-transfer",
    level: "Specialized",
    tags: ["rayleigh", "natural convection", "dimensionless"],
  },
  {
    name: "Peclet Number",
    description: "Calculate Peclet number; ratio of convective to diffusive transport.",
    href: "/calculators/peclet-number",
    category: "heat-mass-transfer",
    level: "Applied",
    tags: ["peclet", "convection", "diffusion"],
  },
  {
    name: "Schmidt Number",
    description: "Calculate Schmidt number; ratio of momentum to mass diffusivity.",
    href: "/calculators/schmidt-number",
    category: "heat-mass-transfer",
    level: "Applied",
    tags: ["schmidt", "mass transfer", "diffusion"],
  },
  {
    name: "Sherwood Number",
    description: "Calculate Sherwood number for convective mass transfer.",
    href: "/calculators/sherwood-number",
    category: "heat-mass-transfer",
    level: "Applied",
    tags: ["sherwood", "mass transfer", "convection"],
  },
  {
    name: "Lewis Number",
    description: "Calculate Lewis number; ratio of thermal to mass diffusivity.",
    href: "/calculators/lewis-number",
    category: "heat-mass-transfer",
    level: "Specialized",
    tags: ["lewis", "heat transfer", "mass transfer"],
  },
  {
    name: "Non-Circular Duct Flow",
    description: "Calculate flow rate and head loss in non-circular ducts using hydraulic diameter.",
    href: "/calculators/non-circular-duct",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["duct", "hydraulic diameter", "non-circular"],
  },
  {
    name: "Lift Force",
    description: "Calculate lift force on an airfoil or wing using lift coefficient.",
    href: "/calculators/lift-force",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["lift", "airfoil", "aerodynamics"],
  },
  {
    name: "Boundary Layer Thickness",
    description: "Calculate boundary layer thickness for flow over flat plates.",
    href: "/calculators/boundary-layer",
    category: "fluid-mechanics-ii",
    level: "Specialized",
    tags: ["boundary layer", "flat plate", "external flow"],
  },
  {
    name: "Flow Work",
    description: "Calculate flow work (PV work) in open systems.",
    href: "/calculators/flow-work",
    category: "fluid-mechanics-i",
    level: "Applied",
    tags: ["work", "energy", "thermodynamics"],
  },
  {
    name: "Momentum Flux",
    description: "Calculate momentum flux for control volume analysis.",
    href: "/calculators/momentum-flux",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["momentum", "control volume", "force"],
  },
  {
    name: "Control Volume Force",
    description: "Calculate force on control volume using momentum equation.",
    href: "/calculators/control-volume-force",
    category: "fluid-mechanics-ii",
    level: "Specialized",
    tags: ["force", "momentum", "control volume"],
  },
  {
    name: "Vortex Flow",
    description: "Calculate properties of rotational vortex flow patterns.",
    href: "/calculators/vortex-flow",
    category: "fluid-mechanics-ii",
    level: "Specialized",
    tags: ["vortex", "rotational", "swirl"],
  },
  {
    name: "Swirl Number",
    description: "Calculate swirl number for swirling flows in pipes and combustors.",
    href: "/calculators/swirl-number",
    category: "fluid-mechanics-ii",
    level: "Specialized",
    tags: ["swirl", "rotational flow", "dimensionless"],
  },
  {
    name: "Dynamic Pressure",
    description: "Calculate dynamic pressure q = ½ρV² and the full Bernoulli pressure decomposition.",
    href: "/calculators/dynamic-pressure",
    category: "fluid-mechanics-i",
    level: "Fundamental",
    tags: ["pressure", "velocity", "dynamic", "Bernoulli"],
  },
  {
    name: "Energy Loss",
    description: "Calculate energy loss in fluid systems from head loss and flow rate.",
    href: "/calculators/energy-loss",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["energy", "loss", "head"],
  },
  {
    name: "Area Ratio",
    description: "Calculate area ratio and its effect on flow properties.",
    href: "/calculators/area-ratio",
    category: "fluid-mechanics-i",
    level: "Fundamental",
    tags: ["area", "ratio", "geometry"],
  },
  {
    name: "Tank Volume Calculator",
    description: "Volume at any liquid level for vertical (flat, cone, hemispherical, ellipsoidal heads), horizontal cylindrical, and rectangular tanks. Strapping table, fill time, contents mass, surface area, and multi-unit output.",
    href: "/calculators/tank-volume",
    category: "fluid-mechanics-i",
    isCore: true,
    level: "Applied",
    tags: ["tank", "volume", "storage", "vessel", "strapping", "fill", "level", "capacity", "ellipsoidal", "hemispherical", "horizontal", "vertical"],
  },
  {
    name: "Flange Pressure Class Rating — ASME B16.5",
    description: "Select minimum ASME B16.5 pressure class (150# to 2500#) for a given design pressure and temperature, or find maximum allowable pressure for a given class. Covers 9 material groups: CS, low-temp CS, 1.25Cr, 2.25Cr, and austenitic SS 304/316/304L/316L. Full interpolated P-T table included.",
    href: "/calculators/flange-rating",
    category: "fluid-mechanics-i",
    isCore: true,
    level: "Applied",
    tags: ["flange", "pressure class", "ASME B16.5", "150#", "300#", "600#", "900#", "1500#", "2500#", "P-T rating", "piping", "pressure rating", "temperature rating"],
  },
  {
    name: "Orifice Plate Sizing — ISO 5167",
    description: "Iterative ISO 5167-2 Reader-Harris/Gallagher sizing: given fluid, pipe diameter, flow rate, and allowable ΔP, computes required beta ratio and bore diameter. Covers liquids and gases (with expansion factor). Corner, D&D/2, and flange tappings. Validates against ISO range limits and shows permanent pressure loss and turndown table.",
    href: "/calculators/orifice-plate-sizing",
    category: "fluid-mechanics-ii",
    isCore: true,
    isDesignTool: true,
    level: "Applied",
    tags: ["orifice plate", "ISO 5167", "beta ratio", "bore diameter", "discharge coefficient", "differential pressure", "flow measurement", "Reader-Harris", "expansion factor", "flange tappings", "corner tappings"],
  },
  {
    name: "Compressor Power — Polytropic & Adiabatic",
    description: "Gas compression power for centrifugal, axial, and reciprocating compressors. Given suction P/T/flow, discharge pressure, gas properties (MW, κ, Z), and isentropic or polytropic efficiency, computes: isentropic head, polytropic head, shaft power, motor power, discharge temperature, polytropic exponent n, and actual volumetric flow at suction and discharge.",
    href: "/calculators/compressor-power",
    category: "turbomachinery",
    isCore: true,
    level: "Applied",
    tags: ["compressor", "polytropic", "isentropic", "adiabatic", "shaft power", "discharge temperature", "compressibility", "centrifugal compressor", "reciprocating compressor", "API 617", "gas compression"],
  },
  {
    name: "Pipe Thermal Expansion & Loop Sizing",
    description: "Calculates thermal expansion ΔL = α·L·ΔT for pipes, sizes U/L/Z expansion loops from guided-cantilever beam theory, checks bending stress vs allowable, computes anchor force if fully restrained, and provides guide spacing. Covers CS, stainless steel, copper, aluminum, HDPE, PVC, CPVC, GRP. Two modes: size the loop or check stress for a given loop.",
    href: "/calculators/pipe-thermal-expansion",
    category: "pipe-networks",
    isCore: true,
    level: "Applied",
    tags: ["thermal expansion", "expansion loop", "U-loop", "L-loop", "pipe stress", "anchor force", "guide spacing", "thermal stress", "ASME B31.3", "alpha coefficient", "pipe flexibility"],
  },
  {
    name: "Slurry Pipeline — Durand & Wilson",
    description: "Critical deposition velocity (Durand-Condolios, F_L factor), head loss for heterogeneous slurry flow, iterative settling velocity and drag coefficient, Wilson-Addie pump de-rating (HR and ER). 9 solid presets (quartz, gold/platinum/chrome tailings, coal, iron ore). Covers Cv/Cw conversion, mixture density, solid mass flow, and validity checks for the Durand heterogeneous flow regime.",
    href: "/calculators/slurry-pipeline",
    category: "pipe-networks",
    isCore: true,
    isDesignTool: true,
    level: "Specialized",
    tags: ["slurry", "Durand", "critical velocity", "deposition velocity", "head loss", "Wilson", "pump de-rating", "mining", "tailings", "heterogeneous flow", "slurry pipeline", "mineral processing"],
  },

  {
    name: "Mine Ventilation — Airway Resistance & Fan Selection",
    description: "Atkinson's equation for mine airway resistance (R = k·L·Per/A³, density-corrected). Series and parallel equivalent circuits. Fan H-Q curve overlay to find the operating point — supports single, 2-fan parallel, and 2-fan series arrangements. Per-airway velocity check. MHSA Reg. 5.15.1 diesel dilution compliance (0.06 m³/s per kW). Air density auto-computed from mine depth via auto-compression. Covers rectangular, arched horseshoe, circular, and square profiles.",
    href: "/calculators/mine-ventilation",
    category: "pipe-networks",
    isCore: true,
    isDesignTool: true,
    level: "Specialized",
    tags: ["mine ventilation", "airway resistance", "Atkinson equation", "fan selection", "fan operating point", "mine fan", "MHSA", "diesel dilution", "underground mining", "series fan", "parallel fan", "auto-compression", "mine airways", "SA mining"],
  },

  // Open Channel Flow
  {
    name: "Manning's Equation",
    description: "Calculate flow velocity or flow rate in open channels using Manning's equation for uniform flow.",
    href: "/calculators/mannings-equation",
    category: "open-channel",
    level: "Fundamental",
    tags: ["manning", "open channel", "uniform flow"],
  },
  {
    name: "Critical Depth",
    description: "Calculate critical depth for open channel flow; depth at minimum specific energy.",
    href: "/calculators/critical-depth",
    category: "open-channel",
    level: "Applied",
    tags: ["critical depth", "open channel", "critical flow"],
  },
  {
    name: "Hydraulic Jump",
    description: "Calculate sequent depths and energy loss in a hydraulic jump.",
    href: "/calculators/hydraulic-jump",
    category: "open-channel",
    level: "Applied",
    tags: ["hydraulic jump", "energy dissipation", "open channel"],
  },
  {
    name: "Weir Flow",
    description: "Calculate flow rate over a weir using weir discharge equations.",
    href: "/calculators/weir-flow",
    category: "open-channel",
    level: "Applied",
    tags: ["weir", "flow rate", "open channel"],
  },
  {
    name: "Specific Energy",
    description: "Calculate specific energy in open channel flow for energy analysis.",
    href: "/calculators/specific-energy",
    category: "open-channel",
    level: "Applied",
    tags: ["specific energy", "open channel", "energy"],
  },
  {
    name: "Normal Depth",
    description: "Calculate normal depth for uniform flow in open channels using Manning's equation.",
    href: "/calculators/normal-depth",
    category: "open-channel",
    level: "Applied",
    tags: ["normal depth", "uniform flow", "manning"],
  },
  {
    name: "Chezy Equation",
    description: "Calculate flow velocity in open channels using Chezy's equation.",
    href: "/calculators/chezy-equation",
    category: "open-channel",
    level: "Applied",
    tags: ["chezy", "open channel", "velocity"],
  },
  {
    name: "Hydraulic Radius",
    description: "Calculate hydraulic radius for open channel flow geometry.",
    href: "/calculators/hydraulic-radius",
    category: "open-channel",
    level: "Fundamental",
    tags: ["hydraulic radius", "geometry", "open channel"],
  },
  {
    name: "Wetted Perimeter",
    description: "Calculate wetted perimeter for various channel cross-sections.",
    href: "/calculators/wetted-perimeter",
    category: "open-channel",
    level: "Fundamental",
    tags: ["wetted perimeter", "geometry", "open channel"],
  },
  {
    name: "Flow Classification",
    description: "Classify open channel flow as subcritical, critical, or supercritical using Froude number.",
    href: "/calculators/flow-classification",
    category: "open-channel",
    level: "Fundamental",
    tags: ["flow regime", "froude number", "open channel"],
  },

  // Open Channel Extensions
  {
    name: "Trapezoidal Channel",
    description: "Calculate flow rate, velocity, and hydraulic properties for a trapezoidal open channel using Manning's equation.",
    href: "/calculators/trapezoidal-channel",
    category: "open-channel",
    level: "Applied",
    tags: ["trapezoidal", "open channel", "manning", "channel design"],
  },
  {
    name: "Culvert Design",
    description: "Calculate flow rate through a culvert under outlet-control conditions using the orifice-type equation.",
    href: "/calculators/culvert-design",
    category: "open-channel",
    level: "Applied",
    tags: ["culvert", "drainage", "outlet control", "hydraulic structures"],
  },
  {
    name: "Sediment Transport (Shields)",
    description: "Determine whether bed sediment is in motion using the Shields dimensionless shear stress criterion.",
    href: "/calculators/sediment-transport",
    category: "open-channel",
    level: "Specialized",
    tags: ["sediment", "shields", "bed load", "scour"],
  },
  {
    name: "Gradually Varied Flow",
    description: "Compute water surface slope and classify the flow profile (M1, M2, S1, S2, etc.) for gradually varied open channel flow.",
    href: "/calculators/gradually-varied-flow",
    category: "open-channel",
    level: "Specialized",
    tags: ["gradually varied", "water surface profile", "backwater curve"],
  },
  {
    name: "Tidal Prism",
    description: "Calculate the tidal prism volume exchanged in an estuary or tidal basin between high and low tide.",
    href: "/calculators/tidal-prism",
    category: "open-channel",
    level: "Specialized",
    tags: ["tidal", "estuary", "coastal hydraulics"],
  },

  // Heat & Mass Transfer Extensions
  {
    name: "Log Mean Temperature Difference (LMTD)",
    description: "Calculate LMTD for counterflow or parallel-flow heat exchangers for sizing and performance analysis.",
    href: "/calculators/lmtd",
    category: "heat-mass-transfer",
    level: "Applied",
    tags: ["lmtd", "heat exchanger", "temperature difference"],
  },
  {
    name: "Overall Heat Transfer Coefficient",
    description: "Calculate the overall U-value from convective and conductive resistances in series including fouling factors.",
    href: "/calculators/overall-htc",
    category: "heat-mass-transfer",
    level: "Applied",
    tags: ["overall U", "heat exchanger", "thermal resistance", "fouling"],
  },
  {
    name: "Dittus-Boelter Correlation",
    description: "Calculate Nusselt number for fully developed turbulent pipe flow using the Dittus-Boelter correlation.",
    href: "/calculators/dittus-boelter",
    category: "heat-mass-transfer",
    level: "Applied",
    tags: ["dittus boelter", "turbulent pipe flow", "nusselt", "forced convection"],
  },
  {
    name: "Natural Convection (Vertical Plate)",
    description: "Calculate Grashof, Rayleigh, and Nusselt numbers for natural convection on a vertical isothermal plate.",
    href: "/calculators/natural-convection-plate",
    category: "heat-mass-transfer",
    level: "Applied",
    tags: ["natural convection", "grashof", "rayleigh", "vertical plate"],
  },
  {
    name: "Effectiveness-NTU Method",
    description: "Calculate heat exchanger effectiveness using the Number of Transfer Units (NTU) method for any flow configuration.",
    href: "/calculators/effectiveness-ntu",
    category: "heat-mass-transfer",
    level: "Specialized",
    tags: ["effectiveness", "ntu", "heat exchanger", "capacity ratio"],
  },
  {
    name: "Fouling Factor",
    description: "Calculate the thermal fouling resistance from clean and fouled heat transfer coefficient measurements.",
    href: "/calculators/fouling-factor",
    category: "heat-mass-transfer",
    level: "Applied",
    tags: ["fouling", "thermal resistance", "heat exchanger maintenance"],
  },
  {
    name: "Fin Efficiency",
    description: "Calculate efficiency of a straight fin with uniform cross-section using the tanh(mL)/(mL) formula.",
    href: "/calculators/fin-efficiency",
    category: "heat-mass-transfer",
    level: "Specialized",
    tags: ["fin", "extended surface", "efficiency", "heat transfer"],
  },
  {
    name: "Thermal Resistance Network",
    description: "Calculate total thermal resistance for a multi-layer wall or pipe with convective boundary conditions.",
    href: "/calculators/thermal-resistance",
    category: "heat-mass-transfer",
    level: "Applied",
    tags: ["thermal resistance", "conduction", "convection", "heat transfer"],
  },

  // Compressible Flow
  {
    name: "Speed of Sound",
    description: "Calculate the speed of sound in an ideal gas from specific heat ratio, gas constant, and temperature.",
    href: "/calculators/speed-of-sound",
    category: "compressible-flow",
    isCore: true,
    level: "Fundamental",
    tags: ["speed of sound", "acoustic velocity", "ideal gas", "compressible"],
  },
  {
    name: "Isentropic Flow Relations",
    description: "Calculate static-to-stagnation ratios (T/T₀, P/P₀, ρ/ρ₀) for isentropic flow at a given Mach number.",
    href: "/calculators/isentropic-relations",
    category: "compressible-flow",
    isCore: true,
    level: "Fundamental",
    tags: ["isentropic", "mach number", "stagnation", "compressible"],
  },
  {
    name: "Normal Shock Relations",
    description: "Calculate downstream Mach number and pressure, temperature, and density ratios across a normal shock wave.",
    href: "/calculators/normal-shock",
    category: "compressible-flow",
    isCore: true,
    level: "Applied",
    tags: ["normal shock", "rankine-hugoniot", "supersonic", "compressible"],
  },
  {
    name: "Stagnation Properties",
    description: "Calculate stagnation (total) temperature and pressure from static conditions and Mach number.",
    href: "/calculators/stagnation-properties",
    category: "compressible-flow",
    level: "Fundamental",
    tags: ["stagnation", "total pressure", "total temperature", "compressible"],
  },
  {
    name: "Choked Flow Rate",
    description: "Calculate the maximum (choked) mass flow rate through a sonic throat for an ideal gas.",
    href: "/calculators/choked-flow",
    category: "compressible-flow",
    level: "Applied",
    tags: ["choked flow", "sonic throat", "mass flow rate", "nozzle"],
  },
  {
    name: "Area-Mach Number Relation",
    description: "Calculate the area ratio A/A* for isentropic flow in a converging-diverging nozzle at a given Mach number.",
    href: "/calculators/area-mach-relation",
    category: "compressible-flow",
    level: "Applied",
    tags: ["area ratio", "nozzle", "throat", "isentropic"],
  },
  {
    name: "Fanno Flow",
    description: "Calculate maximum pipe length for adiabatic flow with friction from a given Mach number to sonic conditions.",
    href: "/calculators/fanno-flow",
    category: "compressible-flow",
    level: "Specialized",
    tags: ["fanno", "friction", "adiabatic pipe", "compressible"],
  },
  {
    name: "Rayleigh Flow",
    description: "Calculate stagnation temperature and pressure ratios for frictionless pipe flow with heat transfer (Rayleigh line).",
    href: "/calculators/rayleigh-flow",
    category: "compressible-flow",
    level: "Specialized",
    tags: ["rayleigh", "heat addition", "pipe flow", "compressible"],
  },
  {
    name: "Oblique Shock Relations",
    description: "Calculate deflection angle, downstream Mach number, and pressure ratio for an oblique shock given wave angle and upstream Mach.",
    href: "/calculators/oblique-shock",
    category: "compressible-flow",
    level: "Specialized",
    tags: ["oblique shock", "wave angle", "deflection angle", "supersonic"],
  },
  {
    name: "Prandtl-Meyer Expansion",
    description: "Calculate downstream Mach number after a Prandtl-Meyer isentropic expansion fan for a given turning angle.",
    href: "/calculators/prandtl-meyer-expansion",
    category: "compressible-flow",
    level: "Specialized",
    tags: ["prandtl meyer", "expansion fan", "isentropic turning", "supersonic"],
  },

  // Turbomachinery
  {
    name: "Pump Head (Euler)",
    description: "Estimate theoretical pump head using the Euler turbomachine equation from impeller geometry and speed.",
    href: "/calculators/pump-head",
    category: "turbomachinery",
    isCore: true,
    level: "Applied",
    tags: ["euler", "pump head", "impeller", "turbomachinery"],
  },
  {
    name: "NPSH (Net Positive Suction Head)",
    description: "Calculate available NPSH to predict and prevent cavitation at the pump inlet.",
    href: "/calculators/npsh",
    category: "turbomachinery",
    isCore: true,
    level: "Applied",
    tags: ["npsh", "cavitation", "pump inlet", "vapor pressure"],
  },
  {
    name: "Specific Speed",
    description: "Calculate dimensionless specific speed to classify pump type (centrifugal, mixed-flow, or axial).",
    href: "/calculators/specific-speed",
    category: "turbomachinery",
    level: "Applied",
    tags: ["specific speed", "pump classification", "dimensionless"],
  },
  {
    name: "Pump Affinity Laws",
    description: "Scale pump performance (flow, head, power) when rotational speed changes using the affinity laws.",
    href: "/calculators/affinity-laws",
    category: "turbomachinery",
    isCore: true,
    level: "Applied",
    tags: ["affinity laws", "pump scaling", "speed change"],
  },
  {
    name: "Hydraulic Efficiency",
    description: "Calculate hydraulic and overall pump efficiency from actual head, Euler head, and shaft power.",
    href: "/calculators/hydraulic-efficiency",
    category: "turbomachinery",
    level: "Applied",
    tags: ["hydraulic efficiency", "pump losses", "overall efficiency"],
  },
  {
    name: "Turbine Power",
    description: "Calculate hydraulic turbine output power from flow rate, head, and turbine efficiency.",
    href: "/calculators/turbine-power",
    category: "turbomachinery",
    isCore: true,
    level: "Applied",
    tags: ["turbine", "hydropower", "turbine efficiency"],
  },
  {
    name: "Fan Laws",
    description: "Scale fan performance (flow, pressure, power) with speed and air density changes using fan similarity laws.",
    href: "/calculators/fan-laws",
    category: "turbomachinery",
    level: "Applied",
    tags: ["fan laws", "HVAC", "fan scaling", "air handling"],
  },
  {
    name: "Impeller Tip Speed",
    description: "Calculate impeller tip (peripheral) speed from diameter and rotational speed.",
    href: "/calculators/impeller-tip-speed",
    category: "turbomachinery",
    level: "Fundamental",
    tags: ["impeller", "tip speed", "peripheral velocity", "rotational speed"],
  },
  {
    name: "Suction Specific Speed",
    description: "Calculate suction specific speed to assess cavitation susceptibility of a pump design.",
    href: "/calculators/suction-specific-speed",
    category: "turbomachinery",
    level: "Specialized",
    tags: ["suction specific speed", "cavitation", "pump design"],
  },

  // Pipe Networks
  {
    name: "Series Pipe System",
    description: "Calculate total head loss for pipes connected in series; same flow rate through each pipe.",
    href: "/calculators/series-pipe",
    category: "pipe-networks",
    isCore: true,
    level: "Applied",
    tags: ["series pipes", "head loss", "pipe network"],
  },
  {
    name: "Parallel Pipe System",
    description: "Distribute flow across parallel pipe branches with equal head loss across each branch.",
    href: "/calculators/parallel-pipe",
    category: "pipe-networks",
    isCore: true,
    level: "Applied",
    tags: ["parallel pipes", "flow distribution", "pipe network"],
  },
  {
    name: "Water Hammer",
    description: "Calculate pressure surge from rapid valve closure using the Joukowsky equation.",
    href: "/calculators/water-hammer",
    category: "pipe-networks",
    level: "Applied",
    tags: ["water hammer", "transient", "pressure surge", "joukowsky"],
  },
  {
    name: "Colebrook-White Equation",
    description: "Solve the implicit Colebrook-White equation iteratively for Darcy friction factor in turbulent pipe flow.",
    href: "/calculators/colebrook-white",
    category: "pipe-networks",
    level: "Applied",
    tags: ["colebrook white", "friction factor", "moody chart", "turbulent"],
  },
  {
    name: "Swamee-Jain Equation",
    description: "Calculate Darcy friction factor using the explicit Swamee-Jain approximation (error < 3%).",
    href: "/calculators/swamee-jain",
    category: "pipe-networks",
    level: "Applied",
    tags: ["swamee jain", "friction factor", "explicit", "turbulent"],
  },
  {
    name: "Hazen-Williams Flow",
    description: "Calculate pipe flow velocity using the Hazen-Williams empirical formula for water supply systems.",
    href: "/calculators/hazen-williams",
    category: "pipe-networks",
    level: "Applied",
    tags: ["hazen williams", "water supply", "pipe flow", "empirical"],
  },
  {
    name: "Pipe Sizing",
    description: "Find the required pipe diameter to deliver a given flow rate within an allowable head loss budget.",
    href: "/calculators/pipe-sizing",
    category: "pipe-networks",
    isCore: true,
    level: "Applied",
    tags: ["pipe sizing", "diameter selection", "design"],
  },
  {
    name: "Hydraulic Gradient",
    description: "Calculate the hydraulic gradient (head loss per unit length) for a pipe segment.",
    href: "/calculators/hydraulic-gradient",
    category: "pipe-networks",
    level: "Fundamental",
    tags: ["hydraulic gradient", "head loss slope", "pipe flow"],
  },
  {
    name: "Pipe Insulation Heat Loss",
    description: "Heat loss per metre and total heat loss from bare or insulated pipes using the cylindrical resistance model. Covers mineral wool, PUR foam, aerogel and more.",
    href: "/calculators/pipe-insulation",
    category: "pipe-networks",
    level: "Applied",
    tags: ["pipe insulation", "heat loss", "thermal resistance", "cylindrical", "insulation thickness"],
  },
  {
    name: "Pipe Schedule Reference",
    description: "Searchable ASME B36.10M/B36.19M pipe schedule table — OD, wall thickness, bore, flow area, and weight for carbon steel and stainless pipe from ⅛\" to 12\".",
    href: "/calculators/pipe-schedule",
    category: "pipe-networks",
    level: "Applied",
    tags: ["pipe schedule", "ASME", "nominal pipe size", "NPS", "OD", "wall thickness", "bore", "carbon steel", "stainless steel"],
  },
  {
    name: "Hydraulic Cylinder & Power",
    description: "Force, piston speed, flow rate, and hydraulic power for extend and retract strokes. Includes hydraulic line velocity check.",
    href: "/calculators/hydraulic-cylinder",
    category: "fluid-mechanics-ii",
    level: "Applied",
    tags: ["hydraulic cylinder", "force", "flow rate", "hydraulic power", "piston", "actuator", "line velocity"],
  },
  {
    name: "Pump System Curve Builder",
    description: "Generate a pipe system H–Q resistance curve, overlay a pump curve to find the operating point. Includes efficiency, shaft power, and affinity-law speed scaling.",
    href: "/calculators/pump-system-curve",
    category: "turbomachinery",
    isCore: true,
    level: "Applied",
    tags: ["pump curve", "system curve", "duty point", "affinity laws", "HVAC", "pump selection", "BEP", "centrifugal pump"],
  },
  {
    name: "Pump Parallel & Series Operation",
    description: "Combine two pump H-Q curves in parallel (flows add) or series (heads add). Finds the combined operating point against a system curve via quadratic curve fitting and bisection. Shows individual pump duties, flow/head gain vs single pump, and warns when one pump is cut out in parallel.",
    href: "/calculators/pump-parallel-series",
    category: "turbomachinery",
    isCore: true,
    level: "Applied",
    tags: ["pump parallel", "pump series", "combined pump curve", "operating point", "pump selection", "dual pump", "booster pump", "pump system"],
  },
  {
    name: "Flow Through Porous Media",
    description: "Darcy's law for permeable media (oil/gas/groundwater) and the Ergun equation for packed beds and granular filters. Computes pressure drop, flow rate, and flow regime.",
    href: "/calculators/flow-porous-media",
    category: "pipe-networks",
    level: "Applied",
    tags: ["Darcy", "Ergun", "porous media", "packed bed", "permeability", "Blake-Kozeny", "pressure drop", "granular filter"],
  },
  {
    name: "Heat Exchanger Quick-Sizer",
    description: "LMTD and effectiveness-NTU sizing for counter-flow, parallel-flow, cross-flow, and 1-2 shell-and-tube exchangers. Solves for area, U-value, or achievable duty.",
    href: "/calculators/heat-exchanger-sizer",
    category: "pipe-networks",
    isCore: true,
    level: "Applied",
    tags: ["heat exchanger", "LMTD", "NTU", "effectiveness", "shell and tube", "counter flow", "U-value", "heat transfer"],
  },
  {
    name: "Psychrometric Calculator",
    description: "Moist-air properties from dry-bulb + any second property (RH, wet-bulb, dew point, or humidity ratio). Outputs enthalpy, humidity ratio, specific volume, density, and comfort zone.",
    href: "/calculators/psychrometric",
    category: "fluid-mechanics-i",
    isCore: true,
    level: "Applied",
    tags: ["psychrometrics", "humidity", "dew point", "wet bulb", "enthalpy", "HVAC", "moist air", "relative humidity"],
  },
  {
    name: "Pipe Roughness Database",
    description: "Searchable table of absolute roughness ε for 28 pipe and duct materials. Enter diameter and Reynolds number to compute ε/D and Darcy friction factor on the fly.",
    href: "/calculators/pipe-roughness",
    category: "pipe-networks",
    level: "Fundamental",
    tags: ["pipe roughness", "absolute roughness", "Moody", "friction factor", "Colebrook", "pipe material", "duct"],
  },
  {
    name: "Pipe Network Solver",
    description: "Nodal Newton-Raphson analysis (Hardy-Cross equivalent) for looped pipe networks. Solves flow distribution, HGL, and pressures at all nodes using Darcy-Weisbach / Colebrook-White.",
    href: "/calculators/pipe-network",
    category: "pipe-networks",
    isCore: true,
    level: "Applied",
    tags: ["Hardy-Cross", "pipe network", "loop network", "flow distribution", "pressure", "HGL", "Newton-Raphson", "Darcy-Weisbach"],
  },
];

// Helper functions
export function getCalculatorsByCategory(categoryId: string): CalculatorInfo[] {
  return allCalculators.filter(calc => calc.category === categoryId && !calc.isDesignTool);
}

export function getCategoryById(categoryId: string) {
  return calculatorCategories.find(cat => cat.id === categoryId);
}

export function searchCalculators(query: string): CalculatorInfo[] {
  const lowerQuery = query.toLowerCase();
  return allCalculators.filter(calc =>
    calc.name.toLowerCase().includes(lowerQuery) ||
    calc.description.toLowerCase().includes(lowerQuery) ||
    calc.tags?.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}

