export interface Formula {
  name: string;
  equation: string;
  description: string;
  where: [string, string][];
  calc?: string;
  tags: string[];
  category: string;
}

export const formulas: Formula[] = [
  // FLUID STATICS
  { name: "Hydrostatic Pressure", equation: "P = P_0 + ρgh", description: "Pressure at depth h in a static fluid", where: [["P", "absolute pressure [Pa]"], ["P₀", "surface pressure [Pa]"], ["ρ", "fluid density [kg/m³]"], ["g", "gravity [m/s²]"], ["h", "depth below surface [m]"]], calc: "/calculators/hydrostatic", tags: ["pressure", "static", "depth"], category: "Fluid Statics" },
  { name: "Buoyancy Force (Archimedes)", equation: "F_B = ρ_f · g · V_{sub}", description: "Upward force on a fully or partially submerged object", where: [["FB", "buoyant force [N]"], ["ρf", "fluid density [kg/m³]"], ["g", "gravity [m/s²]"], ["Vsub", "submerged volume [m³]"]], calc: "/calculators/buoyancy", tags: ["buoyancy", "archimedes", "force"], category: "Fluid Statics" },
  { name: "Manometer Pressure", equation: "ΔP = ρ_m · g · Δh", description: "Pressure difference from a manometer height reading", where: [["ΔP", "pressure difference [Pa]"], ["ρₘ", "manometer fluid density [kg/m³]"], ["g", "gravity [m/s²]"], ["Δh", "height difference [m]"]], calc: "/calculators/manometer", tags: ["pressure", "manometer", "measurement"], category: "Fluid Statics" },
  { name: "Capillary Rise", equation: "h = 4σ cosθ / (ρgd)", description: "Height of liquid rise in a capillary tube due to surface tension", where: [["h", "capillary rise [m]"], ["σ", "surface tension [N/m]"], ["θ", "contact angle [°]"], ["ρ", "liquid density [kg/m³]"], ["g", "gravity [m/s²]"], ["d", "tube diameter [m]"]], calc: "/calculators/capillary-rise", tags: ["capillary", "surface tension", "wetting"], category: "Fluid Statics" },
  { name: "Surface Tension Force", equation: "F = σ · L", description: "Force exerted along a contact line of length L", where: [["F", "surface tension force [N]"], ["σ", "surface tension [N/m]"], ["L", "contact line length [m]"]], calc: "/calculators/surface-tension", tags: ["surface tension", "force", "interface"], category: "Fluid Statics" },

  // CONSERVATION
  { name: "Continuity (Incompressible)", equation: "A_1 V_1 = A_2 V_2 = Q", description: "Conservation of mass for steady, incompressible flow", where: [["A₁", "upstream area [m²]"], ["V₁", "upstream velocity [m/s]"], ["A₂", "downstream area [m²]"], ["V₂", "downstream velocity [m/s]"], ["Q", "volumetric flow rate [m³/s]"]], calc: "/calculators/continuity", tags: ["continuity", "mass conservation", "flow rate"], category: "Conservation" },
  { name: "Mass Flow Rate", equation: "ṁ = ρAV", description: "Mass of fluid passing a cross-section per unit time", where: [["ṁ", "mass flow rate [kg/s]"], ["ρ", "density [kg/m³]"], ["A", "cross-sectional area [m²]"], ["V", "mean velocity [m/s]"]], calc: "/calculators/mass-flow-rate", tags: ["mass flow", "continuity"], category: "Conservation" },
  { name: "Bernoulli's Equation", equation: "P_1/ρg + V_1^2/2g + z_1 = P_2/ρg + V_2^2/2g + z_2", description: "Energy conservation along a streamline (inviscid, incompressible)", where: [["P", "static pressure [Pa]"], ["ρ", "density [kg/m³]"], ["g", "gravity [m/s²]"], ["V", "velocity [m/s]"], ["z", "elevation [m]"]], calc: "/calculators/bernoulli", tags: ["bernoulli", "energy", "streamline"], category: "Conservation" },
  { name: "Dynamic Pressure", equation: "q = (1/2)ρV^2", description: "Kinetic energy per unit volume; also called velocity pressure", where: [["q", "dynamic pressure [Pa]"], ["ρ", "density [kg/m³]"], ["V", "velocity [m/s]"]], calc: "/calculators/dynamic-pressure", tags: ["dynamic pressure", "velocity pressure"], category: "Conservation" },
  { name: "Momentum Equation", equation: "ΣF = ṁ(V_2 - V_1)", description: "Net force equals rate of change of momentum (control volume)", where: [["ΣF", "net external force [N]"], ["ṁ", "mass flow rate [kg/s]"], ["V₂", "outlet velocity [m/s]"], ["V₁", "inlet velocity [m/s]"]], calc: "/calculators/momentum-flux", tags: ["momentum", "force", "control volume"], category: "Conservation" },
  { name: "Extended Energy Equation", equation: "P_1/ρg + V_1^2/2g + z_1 = P_2/ρg + V_2^2/2g + z_2 + h_L", description: "Bernoulli with head loss between two cross-sections", where: [["hL", "total head loss [m]"], ["P", "pressure [Pa]"], ["V", "velocity [m/s]"], ["z", "elevation [m]"], ["ρ", "density [kg/m³]"], ["g", "gravity [m/s²]"]], tags: ["energy equation", "head loss"], category: "Conservation" },

  // PIPE FLOW
  { name: "Reynolds Number", equation: "Re = ρVD/μ = VD/ν", description: "Ratio of inertial to viscous forces; classifies laminar vs turbulent", where: [["Re", "Reynolds number [–]"], ["ρ", "density [kg/m³]"], ["V", "velocity [m/s]"], ["D", "pipe diameter [m]"], ["μ", "dynamic viscosity [Pa·s]"], ["ν", "kinematic viscosity [m²/s]"]], calc: "/calculators/reynolds", tags: ["reynolds", "flow regime", "laminar", "turbulent"], category: "Pipe Flow" },
  { name: "Darcy-Weisbach", equation: "h_f = f(L/D)(V^2/2g)", description: "Head loss due to pipe wall friction", where: [["hf", "friction head loss [m]"], ["f", "Darcy friction factor [–]"], ["L", "pipe length [m]"], ["D", "diameter [m]"], ["V", "mean velocity [m/s]"], ["g", "gravity [m/s²]"]], calc: "/calculators/pipe-head-loss", tags: ["head loss", "darcy-weisbach", "friction", "pipe"], category: "Pipe Flow" },
  { name: "Hagen-Poiseuille", equation: "Q = πD^4 ΔP / (128μL)", description: "Volumetric flow rate for laminar flow in a circular pipe", where: [["Q", "flow rate [m³/s]"], ["D", "diameter [m]"], ["ΔP", "pressure drop [Pa]"], ["μ", "dynamic viscosity [Pa·s]"], ["L", "pipe length [m]"]], calc: "/calculators/poiseuille-flow", tags: ["poiseuille", "laminar", "pressure drop"], category: "Pipe Flow" },
  { name: "Friction Factor — Laminar", equation: "f = 64/Re", description: "Darcy friction factor for laminar pipe flow (Re < 2300)", where: [["f", "Darcy friction factor [–]"], ["Re", "Reynolds number [–]"]], calc: "/calculators/friction-factor", tags: ["friction factor", "laminar", "moody"], category: "Pipe Flow" },
  { name: "Colebrook-White", equation: "1/√f = −2 log(ε/3.7D + 2.51/(Re√f))", description: "Implicit equation for turbulent friction factor (Moody chart basis)", where: [["f", "Darcy friction factor [–]"], ["ε", "absolute roughness [m]"], ["D", "diameter [m]"], ["Re", "Reynolds number [–]"]], calc: "/calculators/colebrook-white", tags: ["colebrook", "turbulent", "friction factor", "moody"], category: "Pipe Flow" },
  { name: "Swamee-Jain", equation: "f = 0.25 / [log(ε/3.7D + 5.74/Re^{0.9})]^2", description: "Explicit approximation of Colebrook-White (error < 3%)", where: [["f", "friction factor [–]"], ["ε", "roughness [m]"], ["D", "diameter [m]"], ["Re", "Reynolds number [–]"]], calc: "/calculators/swamee-jain", tags: ["swamee-jain", "explicit", "friction factor"], category: "Pipe Flow" },
  { name: "Minor Losses", equation: "h_L = K · V^2/2g", description: "Head loss from fittings, valves, bends, entries and exits", where: [["hL", "minor head loss [m]"], ["K", "loss coefficient [–]"], ["V", "velocity [m/s]"], ["g", "gravity [m/s²]"]], calc: "/calculators/minor-losses", tags: ["minor losses", "fittings", "K factor"], category: "Pipe Flow" },
  { name: "Hydraulic Diameter", equation: "D_h = 4A/P", description: "Equivalent diameter for non-circular cross-sections", where: [["Dₕ", "hydraulic diameter [m]"], ["A", "cross-sectional area [m²]"], ["P", "wetted perimeter [m]"]], calc: "/calculators/non-circular-duct", tags: ["hydraulic diameter", "non-circular", "duct"], category: "Pipe Flow" },
  { name: "Water Hammer (Joukowsky)", equation: "ΔP = ρ · a · ΔV", description: "Pressure surge from instantaneous valve closure", where: [["ΔP", "pressure surge [Pa]"], ["ρ", "density [kg/m³]"], ["a", "acoustic wavespeed [m/s]"], ["ΔV", "velocity change [m/s]"]], calc: "/calculators/water-hammer", tags: ["water hammer", "transient", "joukowsky", "surge"], category: "Pipe Flow" },
  { name: "Hazen-Williams", equation: "V = 0.8492 · C · R_h^{0.63} · S^{0.54}", description: "Empirical velocity formula for water supply pipes", where: [["V", "velocity [m/s]"], ["C", "Hazen-Williams roughness coefficient [–]"], ["Rₕ", "hydraulic radius [m]"], ["S", "slope [m/m]"]], calc: "/calculators/hazen-williams", tags: ["hazen-williams", "water supply", "empirical"], category: "Pipe Flow" },

  // EXTERNAL FLOW
  { name: "Drag Force", equation: "F_D = (1/2)ρV^2 A C_D", description: "Aerodynamic drag on a body immersed in flow", where: [["FD", "drag force [N]"], ["ρ", "fluid density [kg/m³]"], ["V", "free-stream velocity [m/s]"], ["A", "reference area [m²]"], ["CD", "drag coefficient [–]"]], calc: "/calculators/drag-sphere", tags: ["drag", "aerodynamics", "external flow"], category: "External Flow" },
  { name: "Lift Force", equation: "F_L = (1/2)ρV^2 A C_L", description: "Aerodynamic lift on an airfoil or wing", where: [["FL", "lift force [N]"], ["ρ", "density [kg/m³]"], ["V", "velocity [m/s]"], ["A", "planform area [m²]"], ["CL", "lift coefficient [–]"]], calc: "/calculators/lift-force", tags: ["lift", "airfoil", "aerodynamics"], category: "External Flow" },
  { name: "Stokes Drag", equation: "F_D = 3πμVD", description: "Drag on a sphere at very low Reynolds number (Re < 1)", where: [["FD", "drag force [N]"], ["μ", "dynamic viscosity [Pa·s]"], ["V", "velocity [m/s]"], ["D", "sphere diameter [m]"]], calc: "/calculators/stokes-law", tags: ["stokes", "creeping flow", "sphere drag"], category: "External Flow" },
  { name: "Boundary Layer Thickness", equation: "δ = 5x/√Re_x", description: "Laminar boundary layer thickness on a flat plate at distance x", where: [["δ", "BL thickness [m]"], ["x", "distance from leading edge [m]"], ["Reₓ", "local Reynolds number Vx/ν [–]"]], calc: "/calculators/boundary-layer", tags: ["boundary layer", "flat plate", "laminar"], category: "External Flow" },

  // DIMENSIONLESS NUMBERS
  { name: "Froude Number", equation: "Fr = V/√(gL)", description: "Ratio of inertial to gravitational forces; governs open channel flow", where: [["Fr", "Froude number [–]"], ["V", "velocity [m/s]"], ["g", "gravity [m/s²]"], ["L", "characteristic length [m]"]], calc: "/calculators/froude-number", tags: ["froude", "open channel", "gravity"], category: "Dimensionless Numbers" },
  { name: "Mach Number", equation: "M = V/c = V/√(γRT)", description: "Ratio of flow speed to local speed of sound", where: [["M", "Mach number [–]"], ["V", "flow velocity [m/s]"], ["c", "speed of sound [m/s]"], ["γ", "specific heat ratio [–]"], ["R", "gas constant [J/kgK]"], ["T", "temperature [K]"]], calc: "/calculators/mach-number", tags: ["mach", "compressible", "speed of sound"], category: "Dimensionless Numbers" },
  { name: "Weber Number", equation: "We = ρV^2 L/σ", description: "Ratio of inertial to surface tension forces", where: [["We", "Weber number [–]"], ["ρ", "density [kg/m³]"], ["V", "velocity [m/s]"], ["L", "length scale [m]"], ["σ", "surface tension [N/m]"]], calc: "/calculators/weber-number", tags: ["weber", "surface tension", "droplets"], category: "Dimensionless Numbers" },
  { name: "Euler Number", equation: "Eu = ΔP/(ρV^2)", description: "Ratio of pressure forces to inertial forces", where: [["Eu", "Euler number [–]"], ["ΔP", "pressure difference [Pa]"], ["ρ", "density [kg/m³]"], ["V", "velocity [m/s]"]], calc: "/calculators/euler-number", tags: ["euler", "pressure", "dimensionless"], category: "Dimensionless Numbers" },
  { name: "Strouhal Number", equation: "St = fL/V", description: "Ratio of unsteady to steady inertia; governs vortex shedding", where: [["St", "Strouhal number [–]"], ["f", "oscillation frequency [Hz]"], ["L", "characteristic length [m]"], ["V", "velocity [m/s]"]], calc: "/calculators/strouhal-number", tags: ["strouhal", "vortex shedding", "unsteady"], category: "Dimensionless Numbers" },
  { name: "Nusselt Number", equation: "Nu = hL/k", description: "Ratio of convective to conductive heat transfer", where: [["Nu", "Nusselt number [–]"], ["h", "convective HTC [W/m²K]"], ["L", "characteristic length [m]"], ["k", "thermal conductivity [W/mK]"]], calc: "/calculators/nusselt-number", tags: ["nusselt", "heat transfer", "convection"], category: "Dimensionless Numbers" },
  { name: "Prandtl Number", equation: "Pr = μc_p/k = ν/α", description: "Ratio of momentum to thermal diffusivity", where: [["Pr", "Prandtl number [–]"], ["μ", "dynamic viscosity [Pa·s]"], ["cₚ", "specific heat [J/kgK]"], ["k", "thermal conductivity [W/mK]"], ["ν", "kinematic viscosity [m²/s]"], ["α", "thermal diffusivity [m²/s]"]], calc: "/calculators/prandtl-number", tags: ["prandtl", "heat transfer", "thermal diffusivity"], category: "Dimensionless Numbers" },
  { name: "Grashof Number", equation: "Gr = gβΔTL^3/ν^2", description: "Ratio of buoyancy to viscous forces; governs natural convection", where: [["Gr", "Grashof number [–]"], ["g", "gravity [m/s²]"], ["β", "thermal expansion coeff [1/K]"], ["ΔT", "temperature difference [K]"], ["L", "length [m]"], ["ν", "kinematic viscosity [m²/s]"]], calc: "/calculators/grashof-number", tags: ["grashof", "natural convection", "buoyancy"], category: "Dimensionless Numbers" },
  { name: "Rayleigh Number", equation: "Ra = Gr · Pr", description: "Product of Grashof and Prandtl; determines natural convection regime", where: [["Ra", "Rayleigh number [–]"], ["Gr", "Grashof number [–]"], ["Pr", "Prandtl number [–]"]], calc: "/calculators/rayleigh-number", tags: ["rayleigh", "natural convection"], category: "Dimensionless Numbers" },
  { name: "Schmidt Number", equation: "Sc = ν/D_m", description: "Ratio of momentum to mass diffusivity; analogous to Prandtl for mass transfer", where: [["Sc", "Schmidt number [–]"], ["ν", "kinematic viscosity [m²/s]"], ["Dₘ", "mass diffusivity [m²/s]"]], calc: "/calculators/schmidt-number", tags: ["schmidt", "mass transfer", "diffusion"], category: "Dimensionless Numbers" },

  // COMPRESSIBLE FLOW
  { name: "Speed of Sound", equation: "c = √(γRT)", description: "Acoustic velocity in an ideal gas", where: [["c", "speed of sound [m/s]"], ["γ", "specific heat ratio [–]"], ["R", "specific gas constant [J/kgK]"], ["T", "absolute temperature [K]"]], calc: "/calculators/speed-of-sound", tags: ["speed of sound", "acoustic", "compressible"], category: "Compressible Flow" },
  { name: "Stagnation Temperature", equation: "T_0 = T[1 + (γ−1)/2 · M^2]", description: "Total temperature when flow is isentropically decelerated to rest", where: [["T₀", "stagnation temperature [K]"], ["T", "static temperature [K]"], ["γ", "specific heat ratio [–]"], ["M", "Mach number [–]"]], calc: "/calculators/stagnation-properties", tags: ["stagnation", "total temperature", "isentropic"], category: "Compressible Flow" },
  { name: "Isentropic Temperature Ratio", equation: "T/T_0 = [1 + (γ−1)/2 · M^2]^{−1}", description: "Static-to-stagnation temperature ratio for isentropic flow", where: [["T", "static temperature [K]"], ["T₀", "stagnation temperature [K]"], ["γ", "specific heat ratio [–]"], ["M", "Mach number [–]"]], calc: "/calculators/isentropic-relations", tags: ["isentropic", "temperature ratio", "mach"], category: "Compressible Flow" },
  { name: "Isentropic Pressure Ratio", equation: "P/P_0 = (T/T_0)^{γ/(γ−1)}", description: "Static-to-stagnation pressure ratio for isentropic flow", where: [["P", "static pressure [Pa]"], ["P₀", "stagnation pressure [Pa]"], ["T", "static temp [K]"], ["T₀", "stagnation temp [K]"], ["γ", "specific heat ratio [–]"]], calc: "/calculators/isentropic-relations", tags: ["isentropic", "pressure ratio", "compressible"], category: "Compressible Flow" },
  { name: "Normal Shock — Downstream Mach", equation: "M_2^2 = (M_1^2 + 2/(γ−1)) / (2γM_1^2/(γ−1) − 1)", description: "Mach number downstream of a normal shock (M₁ must be supersonic)", where: [["M₂", "downstream Mach [–]"], ["M₁", "upstream Mach > 1 [–]"], ["γ", "specific heat ratio [–]"]], calc: "/calculators/normal-shock", tags: ["normal shock", "mach", "supersonic"], category: "Compressible Flow" },
  { name: "Area-Mach Relation", equation: "A/A* = (1/M)[(2/(γ+1))(1+(γ−1)/2·M^2)]^{(γ+1)/(2(γ−1))}", description: "Cross-sectional area ratio relative to the sonic throat area A*", where: [["A", "local duct area [m²]"], ["A*", "throat (sonic) area [m²]"], ["M", "local Mach number [–]"], ["γ", "specific heat ratio [–]"]], calc: "/calculators/area-mach-relation", tags: ["area mach", "nozzle", "throat", "isentropic"], category: "Compressible Flow" },
  { name: "Choked Mass Flow", equation: "ṁ = A* P_0 √(γ/RT_0) · (2/(γ+1))^{(γ+1)/(2(γ−1))}", description: "Maximum (choked) mass flow rate through a sonic throat", where: [["ṁ", "mass flow rate [kg/s]"], ["A*", "throat area [m²]"], ["P₀", "total pressure [Pa]"], ["T₀", "total temperature [K]"], ["γ", "specific heat ratio [–]"], ["R", "gas constant [J/kgK]"]], calc: "/calculators/choked-flow", tags: ["choked flow", "mass flow", "nozzle", "throat"], category: "Compressible Flow" },
  { name: "Fanno Flow — Max Length", equation: "fL*_{max}/D = (1−M^2)/(γM^2) + (γ+1)/(2γ)·ln((γ+1)M^2/(2+(γ−1)M^2))", description: "Maximum pipe length from Mach M to choking (Fanno line)", where: [["f", "Darcy friction factor [–]"], ["L*max", "max length to choking [m]"], ["D", "diameter [m]"], ["M", "local Mach number [–]"], ["γ", "specific heat ratio [–]"]], calc: "/calculators/fanno-flow", tags: ["fanno", "friction", "compressible pipe flow"], category: "Compressible Flow" },

  // TURBOMACHINERY
  { name: "Euler Turbomachine Equation", equation: "H = U_2 V_{u2}/g", description: "Theoretical head imparted by an impeller (no hydraulic losses)", where: [["H", "Euler head [m]"], ["U₂", "impeller tip speed [m/s]"], ["Vᵤ₂", "tangential velocity at outlet [m/s]"], ["g", "gravity [m/s²]"]], calc: "/calculators/pump-head", tags: ["euler", "pump head", "impeller"], category: "Turbomachinery" },
  { name: "Pump / Turbine Power", equation: "P = ρgQH/η", description: "Shaft power required by a pump, or delivered by a turbine", where: [["P", "shaft power [W]"], ["ρ", "density [kg/m³]"], ["g", "gravity [m/s²]"], ["Q", "flow rate [m³/s]"], ["H", "head [m]"], ["η", "overall efficiency [–]"]], calc: "/calculators/pump-power", tags: ["pump power", "turbine", "efficiency"], category: "Turbomachinery" },
  { name: "Pump Affinity Laws", equation: "Q_2/Q_1 = N_2/N_1,  H_2/H_1 = (N_2/N_1)^2,  P_2/P_1 = (N_2/N_1)^3", description: "Scale pump flow, head, and power with rotational speed", where: [["Q", "flow rate [m³/s]"], ["H", "head [m]"], ["P", "power [W]"], ["N₁", "original speed [rpm]"], ["N₂", "new speed [rpm]"]], calc: "/calculators/affinity-laws", tags: ["affinity laws", "pump scaling", "speed"], category: "Turbomachinery" },
  { name: "Specific Speed", equation: "Ω_s = ω√Q / (gH)^{0.75}", description: "Classifies pump type: radial (low Ωs) → mixed → axial (high Ωs)", where: [["Ωₛ", "specific speed [–]"], ["ω", "angular velocity [rad/s]"], ["Q", "flow rate [m³/s]"], ["g", "gravity [m/s²]"], ["H", "head [m]"]], calc: "/calculators/specific-speed", tags: ["specific speed", "pump type", "dimensionless"], category: "Turbomachinery" },
  { name: "NPSH Available", equation: "NPSH_A = (P_s − P_v)/(ρg)", description: "Available suction head above vapour pressure — must exceed NPSH required", where: [["NPSHₐ", "available NPSH [m]"], ["Pₛ", "suction pressure (absolute) [Pa]"], ["Pᵥ", "vapour pressure [Pa]"], ["ρ", "density [kg/m³]"], ["g", "gravity [m/s²]"]], calc: "/calculators/npsh", tags: ["npsh", "cavitation", "pump", "vapour pressure"], category: "Turbomachinery" },
  { name: "Impeller Tip Speed", equation: "U_2 = ω · D/2", description: "Peripheral velocity at the impeller outer diameter", where: [["U₂", "tip speed [m/s]"], ["ω", "angular velocity [rad/s]"], ["D", "impeller diameter [m]"]], calc: "/calculators/impeller-tip-speed", tags: ["impeller", "tip speed", "peripheral velocity"], category: "Turbomachinery" },

  // OPEN CHANNEL FLOW
  { name: "Manning's Equation", equation: "V = (1/n) R_h^{2/3} S^{1/2}", description: "Mean velocity for uniform flow in open channels", where: [["V", "mean velocity [m/s]"], ["n", "Manning's roughness [–]"], ["Rₕ", "hydraulic radius A/P [m]"], ["S", "bed slope [m/m]"]], calc: "/calculators/mannings-equation", tags: ["manning", "open channel", "uniform flow"], category: "Open Channel Flow" },
  { name: "Chezy Equation", equation: "V = C√(R_h S)", description: "Older form of Manning's for uniform open channel flow", where: [["V", "velocity [m/s]"], ["C", "Chezy coefficient [m^{0.5}/s]"], ["Rₕ", "hydraulic radius [m]"], ["S", "slope [m/m]"]], calc: "/calculators/chezy-equation", tags: ["chezy", "open channel", "velocity"], category: "Open Channel Flow" },
  { name: "Critical Depth (Rectangular)", equation: "y_c = (q^2/g)^{1/3}", description: "Flow depth at minimum specific energy in a rectangular channel", where: [["yc", "critical depth [m]"], ["q", "unit discharge Q/b [m²/s]"], ["g", "gravity [m/s²]"]], calc: "/calculators/critical-depth", tags: ["critical depth", "rectangular channel"], category: "Open Channel Flow" },
  { name: "Hydraulic Jump", equation: "y_2/y_1 = (1/2)(−1 + √(1 + 8Fr_1^2))", description: "Sequent depth ratio across a hydraulic jump (rectangular channel)", where: [["y₂", "downstream depth [m]"], ["y₁", "upstream depth [m]"], ["Fr₁", "upstream Froude number [–]"]], calc: "/calculators/hydraulic-jump", tags: ["hydraulic jump", "sequent depth", "energy dissipation"], category: "Open Channel Flow" },
  { name: "Specific Energy", equation: "E = y + V^2/2g", description: "Total energy per unit weight measured from the channel bed", where: [["E", "specific energy [m]"], ["y", "flow depth [m]"], ["V", "velocity [m/s]"], ["g", "gravity [m/s²]"]], calc: "/calculators/specific-energy", tags: ["specific energy", "open channel"], category: "Open Channel Flow" },
  { name: "Rectangular Weir", equation: "Q = (2/3) C_d L √(2g) · H^{3/2}", description: "Discharge over a sharp-crested rectangular weir", where: [["Q", "flow rate [m³/s]"], ["Cd", "discharge coeff ≈ 0.61 [–]"], ["L", "weir length [m]"], ["g", "gravity [m/s²]"], ["H", "head above crest [m]"]], calc: "/calculators/weir-flow", tags: ["weir", "overflow", "discharge"], category: "Open Channel Flow" },
  { name: "Shields Parameter", equation: "τ* = τ / ((ρ_s − ρ)g·d)", description: "Dimensionless bed shear stress; τ* > 0.047 initiates sediment motion", where: [["τ*", "Shields parameter [–]"], ["τ", "bed shear stress [Pa]"], ["ρₛ", "sediment density [kg/m³]"], ["ρ", "fluid density [kg/m³]"], ["g", "gravity [m/s²]"], ["d", "particle diameter [m]"]], calc: "/calculators/sediment-transport", tags: ["shields", "sediment", "bed load"], category: "Open Channel Flow" },

  // HEAT & MASS TRANSFER
  { name: "Newton's Law of Cooling", equation: "q = h · A · (T_w − T_∞)", description: "Convective heat transfer rate from a surface to a fluid", where: [["q", "heat transfer rate [W]"], ["h", "convective HTC [W/m²K]"], ["A", "surface area [m²]"], ["Tw", "wall temperature [K]"], ["T∞", "bulk fluid temperature [K]"]], tags: ["convection", "heat transfer", "newton"], category: "Heat & Mass Transfer" },
  { name: "Fourier's Law of Conduction", equation: "q = −k · A · dT/dx", description: "Conductive heat flux through a material", where: [["q", "heat flux [W]"], ["k", "thermal conductivity [W/mK]"], ["A", "area [m²]"], ["dT/dx", "temperature gradient [K/m]"]], tags: ["conduction", "fourier", "heat flux"], category: "Heat & Mass Transfer" },
  { name: "LMTD", equation: "ΔT_{lm} = (ΔT_1 − ΔT_2) / ln(ΔT_1/ΔT_2)", description: "Log Mean Temperature Difference — effective driving force in a heat exchanger", where: [["ΔTlm", "LMTD [K]"], ["ΔT₁", "temperature difference at end 1 [K]"], ["ΔT₂", "temperature difference at end 2 [K]"]], calc: "/calculators/lmtd", tags: ["lmtd", "heat exchanger", "log mean"], category: "Heat & Mass Transfer" },
  { name: "Overall Heat Transfer Coefficient", equation: "1/U = 1/h_i + R_{f,i} + t/k + R_{f,o} + 1/h_o", description: "Combined thermal resistance for a flat wall with fouling on both sides", where: [["U", "overall HTC [W/m²K]"], ["hᵢ", "inner HTC [W/m²K]"], ["hₒ", "outer HTC [W/m²K]"], ["Rf,i", "inner fouling resistance [m²K/W]"], ["Rf,o", "outer fouling resistance [m²K/W]"], ["t", "wall thickness [m]"], ["k", "wall conductivity [W/mK]"]], calc: "/calculators/overall-htc", tags: ["overall HTC", "U-value", "heat exchanger", "fouling"], category: "Heat & Mass Transfer" },
  { name: "Dittus-Boelter Correlation", equation: "Nu = 0.023 Re^{0.8} Pr^n", description: "Nusselt number for turbulent pipe flow (n = 0.4 heating, 0.3 cooling)", where: [["Nu", "Nusselt number [–]"], ["Re", "Reynolds number [–]"], ["Pr", "Prandtl number [–]"], ["n", "0.4 (fluid heating) or 0.3 (fluid cooling)"]], calc: "/calculators/dittus-boelter", tags: ["dittus-boelter", "turbulent", "pipe heat transfer"], category: "Heat & Mass Transfer" },
  { name: "Fin Efficiency", equation: "η_f = tanh(mL)/(mL),  m = √(hP/kA_c)", description: "Efficiency of a straight fin with uniform cross-section", where: [["ηf", "fin efficiency [–]"], ["m", "fin parameter [m⁻¹]"], ["L", "fin length [m]"], ["h", "HTC [W/m²K]"], ["P", "fin perimeter [m]"], ["k", "conductivity [W/mK]"], ["Ac", "fin cross-section [m²]"]], calc: "/calculators/fin-efficiency", tags: ["fin", "efficiency", "extended surface"], category: "Heat & Mass Transfer" },
  { name: "Heat Exchanger Effectiveness", equation: "ε = Q / Q_{max} = Q / (C_{min}(T_{h,in} − T_{c,in}))", description: "Actual heat transfer as a fraction of thermodynamic maximum", where: [["ε", "effectiveness [–]"], ["Q", "actual heat transfer [W]"], ["Qmax", "maximum possible [W]"], ["Cmin", "smaller heat capacity rate [W/K]"], ["Th,in", "hot-side inlet temp [K]"], ["Tc,in", "cold-side inlet temp [K]"]], calc: "/calculators/effectiveness-ntu", tags: ["effectiveness", "NTU", "heat exchanger"], category: "Heat & Mass Transfer" },
  { name: "Thermal Resistance", equation: "R_{cond} = t/(kA),  R_{conv} = 1/(hA)", description: "Resistance of conductive and convective layers (add in series)", where: [["Rcond", "conductive resistance [K/W]"], ["Rconv", "convective resistance [K/W]"], ["t", "wall thickness [m]"], ["k", "conductivity [W/mK]"], ["h", "convective HTC [W/m²K]"], ["A", "area [m²]"]], calc: "/calculators/thermal-resistance", tags: ["thermal resistance", "conduction", "convection"], category: "Heat & Mass Transfer" },
  { name: "NTU Definition", equation: "NTU = UA / C_{min}", description: "Number of Transfer Units — dimensionless heat exchanger size used in the ε-NTU method", where: [["NTU", "number of transfer units [–]"], ["U", "overall HTC [W/m²K]"], ["A", "heat transfer area [m²]"], ["Cmin", "minimum capacity rate W_dot_{min}·c_p [W/K]"]], calc: "/calculators/effectiveness-ntu", tags: ["NTU", "heat exchanger", "effectiveness", "UA"], category: "Heat & Mass Transfer" },
  { name: "Churchill-Chu (Vertical Plate)", equation: "Nu = (0.825 + 0.387 Ra^{1/6} / [1+(0.492/Pr)^{9/16}]^{8/27})^2", description: "Average Nusselt number for natural convection on an isothermal vertical plate (all Rayleigh numbers)", where: [["Nu", "average Nusselt number [–]"], ["Ra", "Rayleigh number = Gr·Pr [–]"], ["Pr", "Prandtl number [–]"]], calc: "/calculators/natural-convection-plate", tags: ["churchill", "natural convection", "vertical plate", "correlation"], category: "Heat & Mass Transfer" },
  { name: "Colburn Analogy", equation: "St · Pr^{2/3} = C_f / 2", description: "Links heat transfer (Stanton number) to skin friction; allows h to be estimated from friction measurements", where: [["St", "Stanton number h/(ρVc_p) [–]"], ["Pr", "Prandtl number [–]"], ["Cf", "Fanning friction factor [–]"]], tags: ["colburn", "reynolds analogy", "heat-momentum analogy"], category: "Heat & Mass Transfer" },

  // FLUID STATICS — additional
  { name: "Pressure Force on Submerged Plane", equation: "F = ρg · ȳ · A", description: "Resultant hydrostatic force on a flat submerged surface; acts at the centre of pressure (below centroid)", where: [["F", "resultant hydrostatic force [N]"], ["ρ", "fluid density [kg/m³]"], ["g", "gravity [m/s²]"], ["ȳ", "depth to surface centroid [m]"], ["A", "surface area [m²]"]], tags: ["hydrostatic force", "submerged plane", "pressure force"], category: "Fluid Statics" },
  { name: "Centre of Pressure Depth", equation: "y_{cp} = ȳ + I_G / (ȳ · A)", description: "Depth of resultant force below the free surface; always deeper than the centroid for inclined/vertical plates", where: [["ycp", "centre of pressure depth [m]"], ["ȳ", "centroid depth [m]"], ["IG", "second moment of area about centroidal axis [m⁴]"], ["A", "surface area [m²]"]], tags: ["centre of pressure", "hydrostatic", "submerged surface"], category: "Fluid Statics" },
  { name: "Metacentric Height", equation: "GM = I_{WP} / ∇ − BG", description: "Initial stability indicator for a floating body; GM > 0 means stable, GM < 0 means unstable", where: [["GM", "metacentric height [m]"], ["Iwp", "second moment of waterplane area [m⁴]"], ["∇", "submerged (displaced) volume [m³]"], ["BG", "distance from B (buoyancy centre) to G (gravity centre) [m]"]], tags: ["stability", "floating body", "metacentre", "metacentric height"], category: "Fluid Statics" },

  // CONSERVATION — additional
  { name: "Total Head", equation: "H = P/(ρg) + V^2/(2g) + z", description: "Total mechanical energy per unit weight at any cross-section; conserved along a streamline in ideal flow", where: [["H", "total head [m]"], ["P", "static pressure [Pa]"], ["ρ", "density [kg/m³]"], ["g", "gravity [m/s²]"], ["V", "mean velocity [m/s]"], ["z", "elevation [m]"]], tags: ["total head", "energy head", "bernoulli"], category: "Conservation" },
  { name: "Momentum Flux", equation: "J = ρQV = ρAV^2", description: "Rate of momentum transport through a cross-section; appears in control volume force balances", where: [["J", "momentum flux [N]"], ["ρ", "density [kg/m³]"], ["Q", "volumetric flow rate [m³/s]"], ["V", "mean velocity [m/s]"], ["A", "cross-sectional area [m²]"]], calc: "/calculators/momentum-flux", tags: ["momentum flux", "control volume", "momentum"], category: "Conservation" },
  { name: "Ideal Gas Law", equation: "P = ρRT", description: "Equation of state for a perfect gas; links pressure, density, and absolute temperature", where: [["P", "absolute pressure [Pa]"], ["ρ", "density [kg/m³]"], ["R", "specific gas constant [J/kgK]"], ["T", "absolute temperature [K]"]], tags: ["ideal gas", "equation of state", "perfect gas", "compressible"], category: "Conservation" },

  // PIPE FLOW — additional measurement & network formulas
  { name: "Orifice Flow Rate", equation: "Q = C_d · A_o · √(2ΔP/ρ)", description: "Volumetric flow through a sharp-edged orifice plate; C_d ≈ 0.61 for standard orifices", where: [["Q", "flow rate [m³/s]"], ["Cd", "discharge coefficient ≈ 0.61 [–]"], ["Aₒ", "orifice (vena-contracta) area [m²]"], ["ΔP", "pressure drop across orifice [Pa]"], ["ρ", "fluid density [kg/m³]"]], calc: "/calculators/orifice-flow", tags: ["orifice", "flow measurement", "discharge coefficient"], category: "Pipe Flow" },
  { name: "Venturi Flow Rate", equation: "Q = C_v · A_t · √(2ΔP / (ρ(1 − β^4)))", description: "Volumetric flow through a Venturi meter; C_v ≈ 0.98, β = throat/pipe diameter ratio", where: [["Q", "flow rate [m³/s]"], ["Cᵥ", "venturi discharge coefficient ≈ 0.98 [–]"], ["Aₜ", "throat cross-section [m²]"], ["ΔP", "pressure drop [Pa]"], ["ρ", "density [kg/m³]"], ["β", "diameter ratio D_t/D_1 [–]"]], calc: "/calculators/venturi-flow", tags: ["venturi", "flow measurement", "throat", "differential pressure"], category: "Pipe Flow" },
  { name: "Pitot Tube Velocity", equation: "V = √(2(P_0 − P_∞) / ρ)", description: "Free-stream velocity from the difference between stagnation and static pressure", where: [["V", "flow velocity [m/s]"], ["P₀", "stagnation (total) pressure [Pa]"], ["P∞", "static pressure [Pa]"], ["ρ", "fluid density [kg/m³]"]], calc: "/calculators/pitot-tube", tags: ["pitot tube", "velocity measurement", "stagnation pressure"], category: "Pipe Flow" },
  { name: "Torricelli's Theorem", equation: "V = √(2gh)", description: "Exit velocity from a tank orifice at depth h below the free surface (Bernoulli applied to large tank)", where: [["V", "exit velocity [m/s]"], ["g", "gravity [m/s²]"], ["h", "head above orifice centre [m]"]], calc: "/calculators/torricelli", tags: ["torricelli", "tank discharge", "orifice", "free surface"], category: "Pipe Flow" },
  { name: "Total Pressure", equation: "P_0 = P + (1/2)ρV^2", description: "Sum of static and dynamic pressure; constant along a streamline for incompressible inviscid flow", where: [["P₀", "total (stagnation) pressure [Pa]"], ["P", "static pressure [Pa]"], ["ρ", "density [kg/m³]"], ["V", "velocity [m/s]"]], calc: "/calculators/total-pressure", tags: ["total pressure", "stagnation", "dynamic pressure", "bernoulli"], category: "Pipe Flow" },
  { name: "Pressure Recovery Coefficient", equation: "C_p = (P_2 − P_1) / ((1/2)ρV_1^2)", description: "Fraction of dynamic pressure recovered as static pressure in a diffuser", where: [["Cₚ", "pressure recovery coefficient [–]"], ["P₂", "outlet static pressure [Pa]"], ["P₁", "inlet static pressure [Pa]"], ["ρ", "density [kg/m³]"], ["V₁", "inlet velocity [m/s]"]], calc: "/calculators/pressure-recovery", tags: ["pressure recovery", "diffuser", "coefficient"], category: "Pipe Flow" },
  { name: "Cavitation Number", equation: "σ = (P − P_v) / ((1/2)ρV^2)", description: "Dimensionless local pressure margin above vapour pressure; cavitation begins when σ falls below the critical value", where: [["σ", "cavitation number [–]"], ["P", "local absolute pressure [Pa]"], ["Pᵥ", "vapour pressure [Pa]"], ["ρ", "density [kg/m³]"], ["V", "reference velocity [m/s]"]], calc: "/calculators/cavitation-number", tags: ["cavitation", "cavitation number", "vapour pressure"], category: "Pipe Flow" },
  { name: "Hydraulic Gradient", equation: "i = h_f / L", description: "Head loss per unit pipe length; equals the slope of the hydraulic grade line for uniform pipe flow", where: [["i", "hydraulic gradient [m/m]"], ["hf", "friction head loss [m]"], ["L", "pipe length [m]"]], calc: "/calculators/hydraulic-gradient", tags: ["hydraulic gradient", "HGL", "head loss per length"], category: "Pipe Flow" },
  { name: "Series Pipe System", equation: "Q_{series} = const,  h_L = Σh_{f,i}", description: "Pipes in series share the same flow rate; total head loss is the sum of individual losses", where: [["Qseries", "common flow rate [m³/s]"], ["hL", "total head loss [m]"], ["hf,i", "head loss in pipe segment i [m]"]], calc: "/calculators/series-pipe", tags: ["series pipe", "pipe network", "head loss sum"], category: "Pipe Flow" },
  { name: "Parallel Pipe System", equation: "Q = ΣQ_i,  h_{f,1} = h_{f,2} = ⋯", description: "Pipes in parallel share the same head loss; total flow is the sum of branch flows", where: [["Q", "total flow rate [m³/s]"], ["Qᵢ", "flow rate in branch i [m³/s]"], ["hf,i", "head loss across each parallel branch [m]"]], calc: "/calculators/parallel-pipe", tags: ["parallel pipe", "pipe network", "flow split"], category: "Pipe Flow" },

  // EXTERNAL FLOW — additional
  { name: "Stokes Settling Velocity", equation: "V_s = (ρ_p − ρ_f) g d^2 / (18μ)", description: "Terminal velocity of a small sphere settling under gravity at very low Reynolds number (Re < 1)", where: [["Vₛ", "settling velocity [m/s]"], ["ρₚ", "particle density [kg/m³]"], ["ρf", "fluid density [kg/m³]"], ["g", "gravity [m/s²]"], ["d", "particle diameter [m]"], ["μ", "dynamic viscosity [Pa·s]"]], tags: ["settling velocity", "stokes", "particle", "sedimentation"], category: "External Flow" },
  { name: "Average Skin Friction — Laminar Plate", equation: "C_{f,avg} = 1.328 / √Re_L", description: "Average skin-friction drag coefficient over an entire laminar flat plate (Blasius solution)", where: [["Cf,avg", "average skin-friction coefficient [–]"], ["ReL", "plate Reynolds number VL/ν [–]"]], tags: ["skin friction", "flat plate", "laminar", "drag coefficient", "blasius"], category: "External Flow" },
  { name: "Displacement Thickness", equation: "δ* = 1.72x / √Re_x", description: "Effective reduction in flow passage width due to the slower-moving fluid inside the boundary layer", where: [["δ*", "displacement thickness [m]"], ["x", "distance from leading edge [m]"], ["Reₓ", "local Reynolds number Vx/ν [–]"]], calc: "/calculators/boundary-layer", tags: ["displacement thickness", "boundary layer", "flat plate", "blasius"], category: "External Flow" },

  // DIMENSIONLESS NUMBERS — additional
  { name: "Peclet Number", equation: "Pe = Re · Pr = VL / α", description: "Ratio of advective to diffusive heat transport; Pe >> 1 means convection dominates over conduction", where: [["Pe", "Peclet number [–]"], ["Re", "Reynolds number [–]"], ["Pr", "Prandtl number [–]"], ["V", "velocity [m/s]"], ["L", "characteristic length [m]"], ["α", "thermal diffusivity [m²/s]"]], calc: "/calculators/peclet-number", tags: ["peclet", "convection", "thermal diffusion", "heat transfer"], category: "Dimensionless Numbers" },
  { name: "Sherwood Number", equation: "Sh = k_m L / D_{AB}", description: "Dimensionless mass transfer coefficient; mass-transfer analogue of the Nusselt number", where: [["Sh", "Sherwood number [–]"], ["kₘ", "convective mass transfer coefficient [m/s]"], ["L", "characteristic length [m]"], ["DAB", "binary mass diffusivity [m²/s]"]], calc: "/calculators/sherwood-number", tags: ["sherwood", "mass transfer", "convective mass transfer"], category: "Dimensionless Numbers" },
  { name: "Lewis Number", equation: "Le = α / D_{AB} = Sc / Pr", description: "Ratio of thermal to mass diffusivity; Le ≈ 1 for air, important in simultaneous heat and mass transfer", where: [["Le", "Lewis number [–]"], ["α", "thermal diffusivity [m²/s]"], ["DAB", "mass diffusivity [m²/s]"], ["Sc", "Schmidt number [–]"], ["Pr", "Prandtl number [–]"]], calc: "/calculators/lewis-number", tags: ["lewis", "thermal diffusivity", "mass diffusivity", "combined transport"], category: "Dimensionless Numbers" },
  { name: "Stanton Number", equation: "St = Nu / (Re · Pr) = h / (ρVc_p)", description: "Dimensionless heat transfer rate at the wall relative to the thermal capacity of the flow", where: [["St", "Stanton number [–]"], ["Nu", "Nusselt number [–]"], ["Re", "Reynolds number [–]"], ["Pr", "Prandtl number [–]"], ["h", "convective HTC [W/m²K]"], ["ρ", "density [kg/m³]"], ["V", "velocity [m/s]"], ["cₚ", "specific heat [J/kgK]"]], tags: ["stanton", "heat transfer coefficient", "wall flux"], category: "Dimensionless Numbers" },

  // COMPRESSIBLE FLOW — additional
  { name: "Normal Shock Pressure Ratio", equation: "P_2/P_1 = (2γM_1^2 − (γ−1)) / (γ+1)", description: "Static pressure ratio across a normal shock; always greater than 1 (pressure always jumps)", where: [["P₂/P₁", "static pressure ratio [–]"], ["γ", "specific heat ratio [–]"], ["M₁", "upstream Mach number (> 1) [–]"]], calc: "/calculators/normal-shock", tags: ["normal shock", "pressure ratio", "supersonic", "shock wave"], category: "Compressible Flow" },
  { name: "Prandtl-Meyer Function", equation: "ν(M) = √((γ+1)/(γ−1)) arctan(√((γ−1)(M^2−1)/(γ+1))) − arctan(√(M^2−1))", description: "Turning angle for isentropic expansion around a convex corner; Δν = ν₂ − ν₁ gives the flow deflection", where: [["ν", "Prandtl-Meyer angle [rad]"], ["M", "local Mach number [–]"], ["γ", "specific heat ratio [–]"]], calc: "/calculators/prandtl-meyer-expansion", tags: ["prandtl-meyer", "expansion fan", "supersonic", "isentropic turning"], category: "Compressible Flow" },
  { name: "Rayleigh Flow Heat Addition", equation: "T_{0,2}/T_{0,1} = [M_1(1+γM_2^2) / (M_2(1+γM_1^2))]^2", description: "Stagnation temperature ratio for frictionless heat addition in a constant-area duct (Rayleigh line)", where: [["T₀₂/T₀₁", "total temperature ratio [–]"], ["M₁", "inlet Mach number [–]"], ["M₂", "outlet Mach number [–]"], ["γ", "specific heat ratio [–]"]], calc: "/calculators/rayleigh-flow", tags: ["rayleigh flow", "heat addition", "Rayleigh line", "combustion"], category: "Compressible Flow" },

  // TURBOMACHINERY — additional
  { name: "Hydraulic Efficiency", equation: "η_h = gH / (U_2 V_{u2})", description: "Ratio of actual pump head to theoretical Euler head; accounts for internal hydraulic losses", where: [["ηₕ", "hydraulic efficiency [–]"], ["g", "gravity [m/s²]"], ["H", "actual total head developed [m]"], ["U₂", "impeller tip speed [m/s]"], ["Vᵤ₂", "tangential (whirl) velocity at impeller outlet [m/s]"]], calc: "/calculators/hydraulic-efficiency", tags: ["hydraulic efficiency", "pump", "euler head", "impeller"], category: "Turbomachinery" },
  { name: "Suction Specific Speed", equation: "N_{ss} = N√Q / (NPSH_A)^{0.75}", description: "Index relating pump speed and flow to NPSH; keep N_ss < 8500 (US units) to avoid cavitation", where: [["Nss", "suction specific speed [rpm·gpm^{0.5}/ft^{0.75}]"], ["N", "rotational speed [rpm]"], ["Q", "flow rate at BEP [gpm]"], ["NPSHₐ", "available NPSH [ft]"]], calc: "/calculators/suction-specific-speed", tags: ["suction specific speed", "npsh", "cavitation risk", "pump"], category: "Turbomachinery" },
  { name: "Thoma Cavitation Coefficient", equation: "σ = NPSH_A / H", description: "Ratio of available NPSH to pump head; cavitation occurs when σ drops below the critical value σ_c", where: [["σ", "Thoma cavitation coefficient [–]"], ["NPSHₐ", "available net positive suction head [m]"], ["H", "total pump head [m]"]], tags: ["thoma", "cavitation coefficient", "npsh", "pump stability"], category: "Turbomachinery" },
  { name: "Fan Laws (Speed Scaling)", equation: "Q ∝ N,  ΔP ∝ N^2,  P ∝ N^3", description: "Scale fan flow, pressure rise, and power with rotational speed at constant geometry and density", where: [["Q", "volumetric flow rate [m³/s]"], ["ΔP", "total pressure rise [Pa]"], ["P", "shaft power [W]"], ["N", "rotational speed [rpm or rad/s]"]], calc: "/calculators/fan-laws", tags: ["fan laws", "affinity laws", "fan", "speed scaling"], category: "Turbomachinery" },

  // OPEN CHANNEL FLOW — additional
  { name: "Normal Depth Condition", equation: "A · R_h^{2/3} = nQ / S^{1/2}", description: "Implicit equation for normal depth in uniform open channel flow; solved iteratively or by software", where: [["A", "cross-sectional flow area [m²]"], ["Rₕ", "hydraulic radius A/P [m]"], ["n", "Manning's roughness coefficient [–]"], ["Q", "discharge [m³/s]"], ["S", "channel bed slope [m/m]"]], calc: "/calculators/normal-depth", tags: ["normal depth", "Manning", "uniform flow", "open channel"], category: "Open Channel Flow" },
  { name: "Trapezoidal Channel Geometry", equation: "A = (b + zy)y,  P = b + 2y√(1+z^2)", description: "Area and wetted perimeter for a trapezoidal cross-section; z = horizontal run per unit vertical rise", where: [["A", "flow area [m²]"], ["b", "base width [m]"], ["z", "side slope (H : 1V) [–]"], ["y", "flow depth [m]"], ["P", "wetted perimeter [m]"]], calc: "/calculators/trapezoidal-channel", tags: ["trapezoidal channel", "cross-section area", "wetted perimeter"], category: "Open Channel Flow" },
  { name: "V-Notch (Triangular) Weir", equation: "Q = (8/15) C_d √(2g) tan(θ/2) · H^{5/2}", description: "Discharge over a sharp-crested V-notch weir; H^{2.5} relationship makes it accurate at low flows", where: [["Q", "flow rate [m³/s]"], ["Cd", "discharge coefficient ≈ 0.61 [–]"], ["g", "gravity [m/s²]"], ["θ", "notch included angle [°]"], ["H", "head above notch vertex [m]"]], tags: ["v-notch weir", "triangular weir", "discharge measurement", "low flow"], category: "Open Channel Flow" },
];

export const CAT_COLOR: Record<string, { badge: string; border: string; eq: string }> = {
  "Fluid Statics":         { badge: "bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300",        border: "border-blue-200 dark:border-blue-800",    eq: "bg-blue-50 dark:bg-blue-950 border-blue-200 dark:border-blue-800" },
  "Conservation":          { badge: "bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300",    border: "border-green-200 dark:border-green-800",   eq: "bg-green-50 dark:bg-green-950 border-green-200 dark:border-green-800" },
  "Pipe Flow":             { badge: "bg-cyan-100 dark:bg-cyan-900 text-cyan-700 dark:text-cyan-300",        border: "border-cyan-200 dark:border-cyan-800",     eq: "bg-cyan-50 dark:bg-cyan-950 border-cyan-200 dark:border-cyan-800" },
  "External Flow":         { badge: "bg-purple-100 dark:bg-purple-900 text-purple-700 dark:text-purple-300",border: "border-purple-200 dark:border-purple-800",  eq: "bg-purple-50 dark:bg-purple-950 border-purple-200 dark:border-purple-800" },
  "Dimensionless Numbers": { badge: "bg-orange-100 dark:bg-orange-900 text-orange-700 dark:text-orange-300",border: "border-orange-200 dark:border-orange-800",  eq: "bg-orange-50 dark:bg-orange-950 border-orange-200 dark:border-orange-800" },
  "Compressible Flow":     { badge: "bg-red-100 dark:bg-red-900 text-red-700 dark:text-red-300",            border: "border-red-200 dark:border-red-800",       eq: "bg-red-50 dark:bg-red-950 border-red-200 dark:border-red-800" },
  "Turbomachinery":        { badge: "bg-indigo-100 dark:bg-indigo-900 text-indigo-700 dark:text-indigo-300",border: "border-indigo-200 dark:border-indigo-800",  eq: "bg-indigo-50 dark:bg-indigo-950 border-indigo-200 dark:border-indigo-800" },
  "Open Channel Flow":     { badge: "bg-teal-100 dark:bg-teal-900 text-teal-700 dark:text-teal-300",        border: "border-teal-200 dark:border-teal-800",     eq: "bg-teal-50 dark:bg-teal-950 border-teal-200 dark:border-teal-800" },
  "Heat & Mass Transfer":  { badge: "bg-amber-100 dark:bg-amber-900 text-amber-700 dark:text-amber-300",    border: "border-amber-200 dark:border-amber-800",   eq: "bg-amber-50 dark:bg-amber-950 border-amber-200 dark:border-amber-800" },
};

export const DEFAULT_STYLE = { badge: "bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300", border: "border-gray-200 dark:border-gray-700", eq: "bg-gray-50 dark:bg-gray-900 border-gray-200 dark:border-gray-700" };

export const categories = Array.from(new Set(formulas.map((f) => f.category)));
